#----devops_k8s_CI_celeryworker_rs.yaml----#
# 
# To create "celeryworker" ReplicaSet for the Pod with the same name.
#
# Run below command to add or adjust the Replica number:
# $ kubectl apply -f devops_k8s_CI_celeryworker_rs.yaml
#
# Run below command to remove it:
# $ kubectl delete -f devops_k8s_CI_celeryworker_rs.yaml
#
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: celeryworker
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "1"
  template:
    metadata:
      labels:
        app: celeryworker
        version: "1"
    spec:
      containers:
        - name: celeryworker
          image: nlmatics/devops:celeryworker
#--------------End-------------------#
