#---devops_k8s_CD_celeryworker_deployment.yaml---#
#-----------------------------------------#
# ---Deployment "celeryworker" setup:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: celeryworker
  name: celeryworker
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: celeryworker
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Initial Setup"
      labels:
        app: celeryworker
    spec:
      containers:
      - image: nlmatics/devops:celeryworker
        name: celeryworker
        resources:
          requests:
            cpu: "100m"
            memory: "1024Mi"
          limits:
            cpu: "1000m"
            memory: "2048Mi"
#-------------------End-------------------#
