#---devops_k8s_CD_postgres_deployment.yaml---#
#-----------------------------------------#
# ---Deployment "postgres" setup:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: postgres
  name: postgres
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Initial Setup"
      labels:
        app: postgres
    spec:
      containers:
      - image: nlmatics/devops:postgres
        name: postgres
        resources:
          requests:
            cpu: "500m"
        volumeMounts:
        - name: database
          mountPath: "/mnt"
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: database
#-----------------------------------------#
# ---PVC from Dynamic Volume Provisioning:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#-------------------End-------------------#
