#----devops_k8s_CI_frontend_rs.yaml----#
# 
# To create "frontend" ReplicaSet for the Pod with the same name.
#
# Run below command to add or adjust the Replica number:
# $ kubectl apply -f devops_k8s_CI_frontend_rs.yaml
#
# Run below command to remove it:
# $ kubectl delete -f devops_k8s_CI_frontend_rs.yaml
#
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "1"
  template:
    metadata:
      labels:
        app: frontend
        version: "1"
    spec:
      containers:
        - name: frontend
          image: nlmatics/devops:frontend
#--------------End-------------------#
