#---devops_k8s_CD_frontend_deployment.yaml---#
#-----------------------------------------#
# ---Deployment "frontend" setup:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Set Resource Limits"
      labels:
        app: frontend
    spec:
      containers:
      - image: nlmatics/devops:frontend
        name: frontend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "1000m"
            memory: "512Mi"
#-----------------------------------------#
# ---Service "frontend" setup:
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  clusterIP: 10.0.7.172
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30093
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
#-----------------------------------------#
# ---Ingress "frontend-ingree" setup:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  finalizers:
  - networking.gke.io/ingress-finalizer-V2
  generation: 1
  name: frontend-ingress
  namespace: default
spec:
  backend:
    serviceName: frontend
    servicePort: 8080
#-------------------End-------------------#
