default_context:
  project_name: 'nlmatics'
  project_slug: 'nlmatics'
  domain_main: 'nlmatics.com'
  domain_staging: 'stag.nlmatics.com'
  docker_swarm_stack_name_main: 'nlmatics-com'
  docker_swarm_stack_name_staging: 'stag-nlmatics-com'
  secret_key: 'NLMatics'
  first_superuser: 'admin@nlmatics.com'
  first_superuser_password: 'NLMatics'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.nlmatics.com", "https://stag.nlmatics.com", "https://nlmatics.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.nlmatics.net'
  smtp_user: 'admin@nlmatics.net'
  smtp_password: 'NLMatics'
  smtp_emails_from_email: 'info@nlmatics.net'
  postgres_password: 'NLMatics'
  pgadmin_default_user: 'admin@nlmatics.com'
  pgadmin_default_user_password: 'NLMatics'
  traefik_constraint_tag: 'nlmatics.com'
  traefik_constraint_tag_staging: 'stag.nlmatics.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:NLMatics'
  sentry_dsn: 'https://1234abcd:5678ef@sentry.example.com/30'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
